---
repos:
  - hooks:
      - id: yamllint
    repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
  - hooks:
      - id: shellcheck
    repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
