apiVersion: batch/v1
kind: CronJob
metadata:
  name: ws-map-maker
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccount: map-maker
          containers:
          - name: ws-map-maker
            image: image-registry.openshift-image-registry.svc:5000/rhtap-o11y--runtime-int/segment-bridge-job
            imagePullPolicy: Always
            command:
              - "ws-map-maker-job.sh"
            tty: true
            volumeMounts:
            - mountPath: /usr/local/etc/kube-config
              name: kube-config
              readOnly: true
            env:
            - name: KUBECONFIG
              value: ""
            - name: KUBECONFIG_SRC
              value: "/usr/local/etc/kube-config/kube-config"
            - name: CONTEXTS
              value: "rh01 m01"
          volumes:
          - name: kube-config
            secret:
              secretName: kube-config
