---
name: checks on Pull Request
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: pip install -r requirements.lock
      - name: Run pre-commit
        run: pre-commit run --all-files
  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Python dependencies
        run: pip install -r requirements.lock
      - name: Run gitlint on CI with pre-commit
        run: >-
          gitlint --commits origin/${{ github.event.pull_request.base.ref
          }}..HEAD
